const express = require('express');
const callController = require('../controllers/callController');
const { auth } = require('../middleware/auth');

const router = express.Router();
router.get('/channel/:channelId', auth, callController.getActiveCall);
router.post('/channel/:channelId/join', auth, callController.joinCall);
router.post('/:callSessionId/leave', auth, callController.leaveCall);
router.post('/:callSessionId/signal', auth, callController.sendSignal);
router.get('/:callSessionId/signals', auth, callController.pollSignals);
router.get('/:callSessionId/state', auth, callController.getCallState);
router.post('/:callSessionId/raise-hand', auth, callController.raiseHand);
router.post('/:callSessionId/lower-hand', auth, callController.lowerHand);
router.post('/:callSessionId/advance-speaker', auth, callController.advanceSpeaker);
router.get('/:callSessionId/join-request-status', auth, callController.getMyJoinRequestStatus);
router.post('/:callSessionId/join-requests/:requesterId/resolve', auth, callController.resolveJoinRequest);
router.patch('/:callSessionId/settings', auth, callController.updateCallSettings);
router.post('/:callSessionId/participants/:targetUserId/remove', auth, callController.removeParticipant);
router.post('/:callSessionId/advance-phase', auth, callController.advancePhase);
module.exports = router;
