const express = require('express');
const learnController = require('../controllers/learnController');
const placementTestController = require('../controllers/placementTestController');
const { auth } = require('../middleware/auth');
const dictionaryRoutes = require('./dictionaryRoutes');
const practiceRoutes = require('./practiceRoutes');
const readingListeningRoutes = require('./readingListeningRoutes');

const router = express.Router();
router.get('/dashboard', auth, learnController.getDashboard);
router.get('/courses/search', auth, learnController.searchCourses);
router.post('/paths', auth, learnController.generatePath);
router.get('/analytics', auth, learnController.getAnalytics);
router.get('/motivation', auth, learnController.getMotivation);
router.get('/practices', auth, learnController.getPractices);
router.post('/practices/sessions', auth, learnController.startPracticeSession);
router.get('/placement-test', auth, placementTestController.getQuestions);
router.post('/placement-test/submit', auth, placementTestController.submit);
router.use('/dictionary', dictionaryRoutes);
router.use('/practice', auth, practiceRoutes);
router.use('/', auth, readingListeningRoutes);
module.exports = router;
