-- Enable Row Level Security on every public-schema table, closing off the Supabase
-- PostgREST/anon-key attack surface as defense-in-depth (Security Advisor: 39 errors).
-- Safe no-op for this app's own access: Prisma connects as the `postgres` role, which
-- has BYPASSRLS and ignores RLS entirely regardless of whether it's enabled. No policies
-- are added on purpose — this app never uses the anon/authenticated PostgREST roles, so
-- default-deny-everyone-else is exactly the desired outcome.
ALTER TABLE "Achievement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AudioContribution" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CallJoinRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CallParticipant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CallSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CallSignal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Certificate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Channel" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChannelMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Course" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CourseEnrollment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DebateRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DebateVote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DictionaryLookup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LearningGoal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LearningInteraction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LearningPassage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LearningSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Lesson" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LessonProgress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MessageReaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Question" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Quiz" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "QuizAttempt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RolePlayScenario" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SentenceCorrection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SentenceSubmission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SkillSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Space" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SpaceInvite" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SpaceMembership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SpeechAssessment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SpeechSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TechnologyTopic" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VocabularyItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VocabularyProgress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
